IDEIMusic/IDEIMusic/Models/Artist.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace IDEIMusic.Models
{
    public class Artist
    {
        public int ArtistID { get; set; }

        [Required, Display(Name="Artist")]
        public string Name { get; set; }

        public virtual ICollection<Album> Albums { get; set; }
    }
}

IDEIMusic/IDEIMusic/Controllers/ArtistController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IDEIMusic.Models;
using IDEIMusic.DAL;

namespace IDEIMusic.Controllers
{
    public class ArtistController : Controller
    {
        private EditorContext db = new EditorContext();

        // GET: /Artist/
        /*
         *  Listar Artists na base de dados
         * */
        public ActionResult Index()
        {
            return View(db.Artists.ToList());
        }

        //
        // GET: /Artist/Details/5
        /*
         *  Listar informação de um artista na base de dados
         * */

        public ActionResult Details(int id = 0)
        {
            Artist artist = db.Artists.Find(id);
            if (artist == null)
            {
                return HttpNotFound();
            }
            ViewBag.records = db.Records
                .Include(s=>s.Album)
                .Include(s=>s.Album.Artist)
                .Where(t => t.Album.ArtistID == id)
                .ToList();
            
            return View(artist);
        }

        //
        // GET: /Artist/Create
        /*
         *  Formulario para criar artista
         * */

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Artist/Create
        /*
         *  Tratamento do formulario submetido para a criação de um artista
         * */

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Artist artist)
        {
            if (ModelState.IsValid)
            {
                if (!artistExists(artist)) { // Não pode haver artistas com nomes repetidos
                    db.Artists.Add(artist);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            return View(artist);
        }

        //
        // GET: /Artist/Edit/5
        /*
         *  Formulario para editar um artista
         * */
        public ActionResult Edit(int id = 0)
        {
            Artist artist = db.Artists.Find(id);
            if (artist == null)
            {
                return HttpNotFound();
            }
            return View(artist);
        }

        //
        // POST: /Artist/Edit/5
        /*
         *  Tratamento do formulario submetido 
         *  para a edição da informação de  um artista
         * */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Artist artist)
        {
            if (ModelState.IsValid)
            {
                if (!artistExists(artist)) {// Não pode haver artistas com nomes repetidos
                    db.Entry(artist).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View(artist);
        }

        //
        // GET: /Artist/Delete/5
        /*
         * Página de confirmação na remoção de um artista da base de Dados
         * */
        public ActionResult Delete(int id = 0)
        {
            Artist artist = db.Artists.Find(id);
            if (artist == null)
            {
                return HttpNotFound();
            }

            ViewBag.records = db.Records
                .Include(s=>s.Album)
                .Include(s=>s.Album.Artist)
                .Where(t => t.Album.ArtistID == id)
                .ToList();
            return View(artist);
        }

        //
        // POST: /Artist/Delete/5
        /*
         * Confirmação de remoção de artista na base de dados
         * */
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Artist artist = db.Artists.Find(id);
            db.Artists.Remove(artist);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        /*
         * Devolve true se existir um artista em 
         * base de dados com o nome do artista submetido por parametro
         * */
        private bool artistExists(Artist a) {
            Artist artistExists = db.Artists.SingleOrDefault
                (s => s.Name.ToLower() == a.Name.ToLower());
            return artistExists != null;
        }
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

IDEIMusic/IDEIMusic/Controllers/RecordController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IDEIMusic.Models;
using IDEIMusic.DAL;

namespace IDEIMusic.Controllers
{

    [Authorize(Roles="ProductManager")]
    public class RecordController : Controller
    {
        private EditorContext db = new EditorContext();

        //
        // GET: /Record/
        /*
         * Mostrar lista dos Records em base de dados
         * */
        public ActionResult Index()
        {
            var records = db.Records.Include(r => r.Album)
                .Include(r => r.Album.Artist)
                .Include(r => r.Album.Tags);
            return View(records.ToList());
        }

        //
        // GET: /Record/Details/5
        /*
         * Mostrar detalhes de um Record individual
         * */

        public ActionResult Details(int id = 0)
        {
            Record record = db.Records.Include(s => s.Album)
                .Include(s => s.Album.Artist)
                .Single( r => r.RecordID == id);
            if (record == null)
            {
                return HttpNotFound();
            }
            return View(record);
        }

        //
        // GET: /Record/Create
        /*
         * Formulario para criação de um Record
         * */

        public ActionResult Create()
        {
            ViewBag.ArtistID = new SelectList(db.Artists, "ArtistID", "Name");
            return View();
        }

        //
        // POST: /Record/Create
        /*
         * Tratamento de um formulário para criação de um Record
         * */

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RecordFormat,Price")] Record record, FormCollection f)
        {
            string AlbumID = "";
            if(f.AllKeys.Contains("AlbumID")){
                AlbumID = f.GetValue("AlbumID").AttemptedValue;
            }
            
            if (AlbumID != "")
            {
                try {
                    int id = Convert.ToInt32(AlbumID);
                    record.AlbumID = Convert.ToInt32(AlbumID);
                    Record recordExists = db.Records.SingleOrDefault(
                        s => s.AlbumID == id
                        && s.RecordFormat == record.RecordFormat);
                    if (recordExists == null && record.Price >= 0.0m) {
                        if (ModelState.IsValid) {
                            db.Records.Add(record);
                            db.SaveChanges();
                            return RedirectToAction("Index");
                        }
                    }
                }
                catch (Exception) {
                    throw;
                }
            }
            ViewBag.ArtistID = new SelectList(db.Artists, "ArtistID", "Name");
            return View(record);
        }

        //
        // GET: /Record/Edit/5
        /*
         * Edição dos detalhes de um Record
         * */

        public ActionResult Edit(int id = 0)
        {
            Record record = db.Records.Include(s => s.Album)
                .Include(s => s.Album.Artist)
                .Single( r => r.RecordID == id);
            if (record == null)
            {
                return HttpNotFound();
            }

            return View(record);
        }

        //
        // POST: /Record/Edit/5
        /*
         * Tratamento do formulario recebido para edição dos detalhes de um Record
         * */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Record record)
        {
            if (ModelState.IsValid)
            {
                if (record.Price >= 0.0m) {
                    db.Entry(record).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            Record recordToDisplay = db.Records.Include(s => s.Album)
                .Include(s => s.Album.Artist)
                .Single( r => r.RecordID == record.RecordID);
            recordToDisplay.RecordFormat = record.RecordFormat;
            recordToDisplay.Price = record.Price;

            return View(recordToDisplay);
        }

        //
        // GET: /Record/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Record record = db.Records.Include(s => s.Album)
                .Include(s => s.Album.Artist)
                .Single( r => r.RecordID == id);
            if (record == null)
            {
                return HttpNotFound();
            }
            return View(record);
        }

        //
        // POST: /Record/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Record record = db.Records.Find(id);
            db.Records.Remove(record);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        /*
         * Retorna ids e titulos de um artista no formato JSON
         * */
        public ActionResult AjaxGetAlbumsFromArtist(int id)
        {
            var dictionary = db.Albums.Where(s => s.ArtistID == id).ToDictionary(a => a.AlbumID, a => a.Title);
            var ids = new List<int>();
            var titles = new List<string>();
            foreach(var k in dictionary){
                ids.Add(Convert.ToInt32(k.Key.ToString()));
                titles.Add(k.Value.ToString());
            }
            var idsTitles = new { ids, titles};
            return Json(idsTitles, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

IDEIMusic/IDEIMusic/Views/Artist/Create.cshtml
@model IDEIMusic.Models.Artist

@{
    ViewBag.Title = "Add Artist";
}

<h2>Add New Artist</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Artist</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IDEIMusic/IDEIMusic/Views/Artist/Delete.cshtml
@model IDEIMusic.Models.Artist

@{
    ViewBag.Title = "Delete Artist";
}

<h2>Delete Artist</h2>

<h3>Are you sure you want to delete this artist?</h3>
<fieldset>
    <legend>Artist</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div>
        <h4>Records</h4>
        @{
            List<IDEIMusic.Models.Record> records = ViewBag.records;

            if (records.Count > 0)
            {
                @:<table><tr>
                        <th>Album Title</th>
                        <th>Price</th>
                        <th>Format</th>
                        <th></th>
                        @:</tr>
                foreach (var record in records)
                {
                    @:<tr class="tableRow"><td>
                            @(record.Album.Title)
                            @:</td> <td>
                            @(record.Price)
                            @:</td><td>
                            @(record.RecordFormat)
                            @:</td></tr>


                }
                @: </table>
        }
            else
            {
                @:No Records on system
            }
        }
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

IDEIMusic/IDEIMusic/Views/Artist/Details.cshtml
@model IDEIMusic.Models.Artist

@{
    ViewBag.Title = Model.Name;
}

<h2>Artist Information</h2>

<fieldset>
    <legend>Artist</legend>

    <div>
        <div class="display-label">
            @Html.DisplayNameFor(model => model.Name)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Name)
        </div>
    </div>
    <div>
        <h4>Records</h4>
        @{
            List<IDEIMusic.Models.Record> records = ViewBag.records;
            
        if (records.Count > 0)
        {
            @:<table><tr>
                <th>Album Title</th>
            <th>Price</th>
            <th>Format</th>
            <th></th>
            @:</tr>
                foreach (var record in records)
                {
                    @:<tr class="tableRow"><td>
                        @(record.Album.Title)
                    @:</td><td>
                        @(record.Price)
                    @:</td><td>
                        @(record.RecordFormat)
                    @:</td><td>
                        @Html.ActionLink("Edit Record", "Edit", "Record", new { id = record.RecordID}, null)
                    @:</td></tr>

                }
            @:</table>
        }
        else
        {
            @:No Records on system
            }
        }
    </div>

</fieldset>
<p>
    @Html.ActionLink("Edit Artist", "Edit", new { id = Model.ArtistID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

IDEIMusic/IDEIMusic/Views/Artist/Edit.cshtml
@model IDEIMusic.Models.Artist

@{
    ViewBag.Title = "Edit Artist Information";
}

<h2>Edit Artist Information</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Artist</legend>

        @Html.HiddenFor(model => model.ArtistID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IDEIMusic/IDEIMusic/Views/Artist/Index.cshtml
@model IEnumerable<IDEIMusic.Models.Artist>

@{
    ViewBag.Title = "Artists";
}

<h2>Artists</h2>

<p>
    @Html.ActionLink("Add New Artist", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ArtistID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ArtistID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ArtistID })
        </td>
    </tr>
}

</table>