IDEIMusic/IDEIMusic/Models/Sale.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace IDEIMusic.Models
{
    public class Sale
    {
        public int SaleID { get; set; }
        public int RecordID { get; set; }

        public int Quantity { get; set; }

        [DisplayFormat(DataFormatString="{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Date { get; set; }

        public virtual Record Record { get; set; }
    }
}

IDEIMusic/IDEIMusic/Controllers/SalesController.cs
using IDEIMusic.DAL;
using IDEIMusic.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IDEIMusic.Controllers {
    [Authorize(Roles = "Admin")]
    public class SalesController : Controller {
        EditorContext db = new EditorContext();
        //
        // GET: /Sales/

        [Authorize(Roles = "Admin")]
        public ActionResult Index(int year = -1, int month = -1) {
            DateTime now = DateTime.Now;
            int salesYear, salesMonth;
            if (year == -1 || month == -1) {
                salesYear = now.Year;
                salesMonth = now.Month;
            }
            else {
                salesYear = year;
                salesMonth = month;
            }
            if (now.Year < salesYear )
                salesYear = now.Year;
            if (salesMonth < 1 || salesMonth > 12)
                salesMonth = 1;
            ViewBag.year = salesYear;
            ViewBag.monthName = new DateTime(salesYear, salesMonth, 1).ToString("MMMM", CultureInfo.InvariantCulture);
            CalculateSalesByFormat(salesYear, salesMonth);
            CalculateSalesByTags(salesYear, salesMonth);
            CalculateSalesByArtist(salesYear, salesMonth);
            return View();
        }
        private void CalculateSalesByArtist(int year, int month) {
            var artistSalesKVPair = new Dictionary<string, int>();
            var sales = db.Sales.Where(
                                 s => s.Date.Year == year
                                 && s.Date.Month == month).ToList();
            foreach (Sale s in sales) {
                if (artistSalesKVPair.ContainsKey(s.Record.Album.Artist.Name)) {
                    artistSalesKVPair[s.Record.Album.Artist.Name] += s.Quantity;
                }
                else {
                    artistSalesKVPair[s.Record.Album.Artist.Name] = s.Quantity;
                }
            }

            ViewBag.SalesByArtist = artistSalesKVPair;

        }

        private void CalculateSalesByTags(int year, int month) {
            var keyValuePairs = new Dictionary<string, int>();
            List<Sale> sales = db.Sales.Where(
                                    s => s.Date.Year == year
                                    && s.Date.Month == month).ToList();
            foreach (Sale s in sales) {
                foreach (Tag t in s.Record.Album.Tags) {
                    if (keyValuePairs.ContainsKey(t.Text)) {
                        keyValuePairs[t.Text] += s.Quantity;
                    }
                    else {
                        keyValuePairs[t.Text] = s.Quantity;
                    }
                }
            }
            ViewBag.SalesByTags = keyValuePairs;

        }

        private void CalculateSalesByFormat(int year, int month) {
            var vinylSales = db.Sales.Where(
                                    s => s.Date.Year == year
                                    && s.Date.Month == month
                                    && s.Record.RecordFormat == Models.RecordFormat.Vinyl);
            if (vinylSales.Count() > 0) {
                ViewBag.VinylSales = vinylSales.Select(s => s.Quantity).Sum();
            }
            else {
                ViewBag.VinylSales = 0;
            }
            var cdSales = db.Sales.Where(
                                s => s.Date.Year == year
                                && s.Date.Month == month
                                && s.Record.RecordFormat == Models.RecordFormat.CD);
            if (cdSales.Count() > 0) {
                ViewBag.CDSales = cdSales.Select(s => s.Quantity).Sum();
            }
            else {
                ViewBag.CDSales = 0;
            }
        }

    }
}

IDEIMusic/IDEIMusic/Views/Sales/Index.cshtml
@{
    ViewBag.Title = "Sales statistics";
}




@using (Html.BeginForm("Index","Sales",FormMethod.Get)) {
    @Html.AntiForgeryToken()
        <p>
        <div>Choose month</div>
        <input type="text" name="month" id="month"/>
        <div id="monthErrorMsg" class="field-validation-error" ></div>
    </p>
    <p>
        <div>Choose Year</div>
        <input type="text" name="year" id="year" />
        <div id="yearErrorMsg" class="field-validation-error"></div>
    </p>
    <p>
    <input type="submit" value="Review sales" id="submitButton"/>
    </p>
}

<h2>Sales statistics for @ViewBag.monthName @ViewBag.year</h2>

<div>
    <h3>Sales by Format</h3>
    <table>
        <tr>
            <th>Format</th>
            <th>Number of Sales</th>
        </tr>
        <tr class="tableRow"><td>Vinyl</td><td>@ViewBag.VinylSales</td></tr>
        <tr class="tableRow">
            <td>
                CD
            </td>
            <td>
                @ViewBag.CDSales
            </td>
        </tr>
    </table>
</div>

<div>
    <h3>Sales by Tags</h3>
    <table>
        <tr>
            <th>Tag</th>
            <th>Number of Sales</th>
        </tr>
        @{
            foreach (KeyValuePair<string, int> kv in ViewBag.SalesByTags)
        {
            <tr class="tableRow"><td>
              @kv.Key.ToString()  
            </td><td>
              @kv.Value.ToString()
            </td></tr>
        }
        }
    </table>
</div>

<div>
    <h3>Sales by Artist</h3>
    <table>
        <tr>
            <th>Artist</th>
            <th>Number of Sales</th>
        </tr>
        @{
            foreach (KeyValuePair<string, int> kv in ViewBag.SalesByArtist)
            {
                <tr class="tableRow">
                    <td>
                        @kv.Key.ToString()
                    </td>
                    <td>
                        @kv.Value.ToString()
                    </td>
                </tr>
            }
        }
    </table>
</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script type="text/javascript">
    $("#month").on("change", function () {

        var mesVal = $("#month").val().toString();
        if (isNaN(mesVal)) {
            $("#monthErrorMsg").text("Not valid month number");
            $("#submitButton").attr("disabled", "disabled");
            return;

        }
        mesNum = parseInt(mesVal);

        if (mesNum < 1 || mesNum > 12) {
            $("#monthErrorMsg").text("Not valid month number");
            $("#submitButton").attr("disabled", "disabled");
            return;
        }

        $("#monthErrorMsg").text("");
        $("#submitButton").removeAttr("disabled");

    });


    $("#year").on("change", function () {

        var yearVal = $("#year").val().toString();
        if (isNaN(yearVal)) {
            $("#yearErrorMsg").text("Not valid year number");
            $("#submitButton").attr("disabled", "disabled");
            return;

        }
        yearNum = parseInt(yearVal);

        if (yearNum < 2000 || yearNum > (new Date).getFullYear()) {
            $("#yearErrorMsg").text("Not valid year number");
            $("#submitButton").attr("disabled", "disabled");
            return;
        }

        $("#yearErrorMsg").text("");
        $("#submitButton").removeAttr("disabled");

    });
</script>

IDEIMusic/IDEIMusic/Views/Sales/StatisticsOfMonth.cshtml
@{
    ViewBag.Title = @ViewBag.monthName + " "+ @ViewBag.year +" Sales statistics";
}

<h2>Sales statistics for @ViewBag.monthName @ViewBag.year</h2>

<div>
    <h3>Sales by Format</h3>
    <table>
        <tr>
            <th>Format</th>
            <th>Number of Sales</th>
        </tr>
        <tr class="tableRow"><td>Vinyl</td><td>@ViewBag.VinylSales</td></tr>
        <tr class="tableRow">
            <td>
                CD
            </td>
            <td>
                @ViewBag.CDSales
            </td>
        </tr>
    </table>
</div>

<div>
    <h3>Sales by Tags</h3>
    <table>
        <tr>
            <th>Tag</th>
            <th>Number of Sales</th>
        </tr>
        @{
            foreach (KeyValuePair<string, int> kv in ViewBag.SalesByTags)
            {
                <tr class="tableRow">
                    <td>
                        @kv.Key.ToString()
                    </td>
                    <td>
                        @kv.Value.ToString()
                    </td>
                </tr>
            }
        }
    </table>
</div>

<div>
    <h3>Sales by Artist</h3>
    <table>
        <tr>
            <th>Artist</th>
            <th>Number of Sales</th>
        </tr>
        @{
            foreach (KeyValuePair<string, int> kv in ViewBag.SalesByArtist)
            {
                <tr class="tableRow">
                    <td>
                        @kv.Key.ToString()
                    </td>
                    <td>
                        @kv.Value.ToString()
                    </td>
                </tr>
            }
        }
    </table>
</div>