IDEIMusic/IDEIMusic/Models/Record.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace IDEIMusic.Models
{

    public enum RecordFormat
    {
        Vinyl, CD
    }

    public class Record
    {
        public int RecordID { get; set; }

        public int AlbumID { get; set; }

        [Display(Name = "Format")]
        public RecordFormat RecordFormat { get; set; }

        [DataType(DataType.Currency)]
        [Range(0.0,10000)]
        public decimal Price { get; set; }

        public virtual Album Album { get; set; }
    }
}

IDEIMusic/IDEIMusic/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IDEIMusic.Models;
using IDEIMusic.DAL;
using IDEIMusic.ViewModels;

namespace IDEIMusic.Controllers {

    [Authorize(Roles = "ProductManager")]
    public class AlbumController : Controller {
        private EditorContext db = new EditorContext();

        //
        // GET: /Album/
        /*
         * Mostrar lista de albums em base de dados
         * */
        public ActionResult Index() {
            var albums = db.Albums.Include(a => a.Artist);
            return View(albums.ToList());
        }

        //
        // GET: /Album/Details/5
        /*
         * Mostrar detalhes de um album em base de dados
         * */

        public ActionResult Details(int id = 0) {
            Album album = db.Albums.Find(id);
            if (album == null) {
                return HttpNotFound();
            }
            return View(album);
        }

        //
        // GET: /Album/Create

        /*
         * Formulario para criação de um album
         * */
        public ActionResult Create() {
            Album album = new Album();
            album.Tags = new List<Tag>();
            PopulateAssignedTagsData(album); // Permite à view aceder a todas as tags
            return View();
        }

        //
        // POST: /Album/Create

        /*
         * Tratamento do formulario submetido para criação de album
         * */

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FormCollection values, string[] selectedTags) {
            Album album = new Album();
            album.Tags = new List<Tag>();

            try {
                // Obter valores do formulario
                string artistName = values.GetValue("artist.Name").AttemptedValue;
                string albumTitle = values.GetValue("Title").AttemptedValue;

                album.Title = albumTitle;

                Artist artist = db.Artists
                    .FirstOrDefault(
                    a => a.Name.ToLower() == artistName.ToLower()); // comparação ignorando capitalização

                if (artist == null) // se o artista não existir, criar
                {
                    artist = new Artist();
                    artist.Name = artistName;
                }

                album.Artist = artist;

                UpdateAlbumTags(selectedTags, album); // obter quais foram as tags seleccionadas

                if (ModelState.IsValid) {
                    if(!albumExists(album)){
                        db.Albums.Add(album);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }

            }
            catch (DataException) {

            }

            PopulateAssignedTagsData(album);
            return View(album);
        }

        //
        // GET: /Album/Edit/5
        /*
         * Edição da informação de um album
         * */

        public ActionResult Edit(int id = 0) {
            Album album = db.Albums
                .Include(i => i.Tags)
                .Include(i => i.Artist)
                .Where(i => i.AlbumID == id)
                .Single();
            if (album == null) {
                return HttpNotFound();
            }

            PopulateAssignedTagsData(album); // Permite à view aceder às tags (escolhidas e não escolhidas)
            return View(album);
        }



        //
        // POST: /Album/Edit/5
        /*
         * Tratamento do formulario enviado para edição de um album
         * */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, FormCollection collection, string[] selectedTags) {
            Album album = db.Albums
                .Include(i => i.Tags)
                .Include(i => i.Artist)
                .Where(i => i.AlbumID == id)
                .Single();

            if (album == null) {
                return HttpNotFound();
            }

            if (TryUpdateModel(album, "", new string[] { "Title" })) {
                try {
                    UpdateAlbumTags(selectedTags, album);

                    db.Entry(album).State = EntityState.Modified;
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (DataException /* dex */) {

                }

            }

            return View(album);
        }



        // GET: /Album/Delete/5
        /*
         * Pedido de confirmação da remoção de um album
         * */
        public ActionResult Delete(int id = 0) {
            Album album = db.Albums.Find(id);
            if (album == null) {
                return HttpNotFound();
            }
            return View(album);
        }

        //
        // POST: /Album/Delete/5
        /*
         * Confirmação da remoção de um album
         * */

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id) {
            Album album = db.Albums.Find(id);
            db.Albums.Remove(album);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        /*
         * Dado um album e uma lista de tags seleccionada, actualizar as tags do album
         * */
        private void UpdateAlbumTags(string[] selectedTags, Album album) {
            if (selectedTags == null) {
                album.Tags = new List<Tag>();
                return;
            }

            var selectedTagsHS = new HashSet<string>(selectedTags);
            var albumTags = new HashSet<int>(album.Tags.Select(t => t.TagID));

            foreach (var tag in db.Tags) {
                if (selectedTagsHS.Contains(tag.TagID.ToString())) {
                    if (!albumTags.Contains(tag.TagID)) {
                        album.Tags.Add(tag);
                    }
                }
                else {
                    if (albumTags.Contains(tag.TagID)) {
                        album.Tags.Remove(tag);
                    }
                }
            }
        }


        /*
         * Obter as tags todas e indicar quais seleccionadas
         * */
        private void PopulateAssignedTagsData(Album album) {
            var allTags = db.Tags;
            var albumTags = new HashSet<int>(album.Tags.Select(t => t.TagID));
            var viewModel = new List<AssignedTagsData>();
            foreach (var tag in allTags) {
                viewModel.Add(new AssignedTagsData {
                    TagID = tag.TagID,
                    Text = tag.Text,
                    Assigned = albumTags.Contains(tag.TagID)
                }
                    );
            }
            ViewBag.Tags = viewModel;
        }

        private bool albumExists(Album albumToCheck) {
            Album albumInDb = db.Albums.SingleOrDefault(s => 
                s.Title.ToLower() == albumToCheck.Title.ToLower() && 
                s.Artist.Name.ToLower() == albumToCheck.Artist.Name.ToLower());
            return albumInDb != null;
        }

        protected override void Dispose(bool disposing) {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

IDEIMusic/IDEIMusic/Controllers/RecordController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IDEIMusic.Models;
using IDEIMusic.DAL;

namespace IDEIMusic.Controllers
{

    [Authorize(Roles="ProductManager")]
    public class RecordController : Controller
    {
        private EditorContext db = new EditorContext();

        //
        // GET: /Record/
        /*
         * Mostrar lista dos Records em base de dados
         * */
        public ActionResult Index()
        {
            var records = db.Records.Include(r => r.Album)
                .Include(r => r.Album.Artist)
                .Include(r => r.Album.Tags);
            return View(records.ToList());
        }

        //
        // GET: /Record/Details/5
        /*
         * Mostrar detalhes de um Record individual
         * */

        public ActionResult Details(int id = 0)
        {
            Record record = db.Records.Include(s => s.Album)
                .Include(s => s.Album.Artist)
                .Single( r => r.RecordID == id);
            if (record == null)
            {
                return HttpNotFound();
            }
            return View(record);
        }

        //
        // GET: /Record/Create
        /*
         * Formulario para criação de um Record
         * */

        public ActionResult Create()
        {
            ViewBag.ArtistID = new SelectList(db.Artists, "ArtistID", "Name");
            return View();
        }

        //
        // POST: /Record/Create
        /*
         * Tratamento de um formulário para criação de um Record
         * */

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RecordFormat,Price")] Record record, FormCollection f)
        {
            string AlbumID = "";
            if(f.AllKeys.Contains("AlbumID")){
                AlbumID = f.GetValue("AlbumID").AttemptedValue;
            }
            
            if (AlbumID != "")
            {
                try {
                    int id = Convert.ToInt32(AlbumID);
                    record.AlbumID = Convert.ToInt32(AlbumID);
                    Record recordExists = db.Records.SingleOrDefault(
                        s => s.AlbumID == id
                        && s.RecordFormat == record.RecordFormat);
                    if (recordExists == null && record.Price >= 0.0m) {
                        if (ModelState.IsValid) {
                            db.Records.Add(record);
                            db.SaveChanges();
                            return RedirectToAction("Index");
                        }
                    }
                }
                catch (Exception) {
                    throw;
                }
            }
            ViewBag.ArtistID = new SelectList(db.Artists, "ArtistID", "Name");
            return View(record);
        }

        //
        // GET: /Record/Edit/5
        /*
         * Edição dos detalhes de um Record
         * */

        public ActionResult Edit(int id = 0)
        {
            Record record = db.Records.Include(s => s.Album)
                .Include(s => s.Album.Artist)
                .Single( r => r.RecordID == id);
            if (record == null)
            {
                return HttpNotFound();
            }

            return View(record);
        }

        //
        // POST: /Record/Edit/5
        /*
         * Tratamento do formulario recebido para edição dos detalhes de um Record
         * */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Record record)
        {
            if (ModelState.IsValid)
            {
                if (record.Price >= 0.0m) {
                    db.Entry(record).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            Record recordToDisplay = db.Records.Include(s => s.Album)
                .Include(s => s.Album.Artist)
                .Single( r => r.RecordID == record.RecordID);
            recordToDisplay.RecordFormat = record.RecordFormat;
            recordToDisplay.Price = record.Price;

            return View(recordToDisplay);
        }

        //
        // GET: /Record/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Record record = db.Records.Include(s => s.Album)
                .Include(s => s.Album.Artist)
                .Single( r => r.RecordID == id);
            if (record == null)
            {
                return HttpNotFound();
            }
            return View(record);
        }

        //
        // POST: /Record/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Record record = db.Records.Find(id);
            db.Records.Remove(record);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        /*
         * Retorna ids e titulos de um artista no formato JSON
         * */
        public ActionResult AjaxGetAlbumsFromArtist(int id)
        {
            var dictionary = db.Albums.Where(s => s.ArtistID == id).ToDictionary(a => a.AlbumID, a => a.Title);
            var ids = new List<int>();
            var titles = new List<string>();
            foreach(var k in dictionary){
                ids.Add(Convert.ToInt32(k.Key.ToString()));
                titles.Add(k.Value.ToString());
            }
            var idsTitles = new { ids, titles};
            return Json(idsTitles, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

IDEIMusic/IDEIMusic/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IDEIMusic.Models;
using IDEIMusic.DAL;

namespace IDEIMusic.Controllers
{
    public class TagController : Controller
    {
        private EditorContext db = new EditorContext();

        //
        // GET: /Tag/
        /*
         * Mostrar lista de tags
         * */
        public ActionResult Index()
        {
            return View(db.Tags.ToList());
        }

        //
        // GET: /Tag/Details/5
        /*
         * Mostrar detalhes de uma tag
         * */
        public ActionResult Details(int id = 0)
        {
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        //
        // GET: /Tag/Create
        /*
         * Formulario para criar tag
         * */
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Tag/Create
        /*
         * Tratamento de formulario submetido para criar uma tag
         * */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Tag tag)
        {
            if (ModelState.IsValid)
            {
                if (!tagExists(tag)) {
                    tag.Text = tag.Text.ToLower();
                    db.Tags.Add(tag);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            return View(tag);
        }

        //
        // GET: /Tag/Edit/5
        /*
         * Formulario para editar uma tag especifica
         * */

        public ActionResult Edit(int id = 0)
        {
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        //
        // POST: /Tag/Edit/5
        /*
         * Formulario submetido para editar uma tag
         * */

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Tag tag)
        {
            if (ModelState.IsValid)
            {
                if (!tagExists(tag)) {
                    tag.Text = tag.Text.ToLower();
                    db.Entry(tag).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View(tag);
        }

        //
        // GET: /Tag/Delete/5
        /*
         * Formulario para confirmação da remoção de uma tag
         * */
        public ActionResult Delete(int id = 0)
        {
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        //
        // POST: /Tag/Delete/5
        /*
         * Confirmação da remoção
         * */
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tag tag = db.Tags.Find(id);
            db.Tags.Remove(tag);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        protected bool tagExists(Tag t) {
            Tag tagInDb = db.Tags.SingleOrDefault(a => a.Text.ToLower() == t.Text.ToLower());
            return tagInDb != null;
        }
    }
}

IDEIMusic/IDEIMusic/Views/Record/Create.cshtml
@model IDEIMusic.Models.Record

@{
    ViewBag.Title = "Add a Record";
}

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<h2>Add Record</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Record</legend>


        <div class="editor-label">
            @Html.LabelFor(model => model.Album.Artist, "Artist")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ArtistID", String.Empty)
            @Html.ValidationMessageFor(model => model.Album.ArtistID)
        </div>

        <div id="albumSelectDiv" hidden="hidden">
            <select name="AlbumID" id="AlbumID"></select>
            @Html.ActionLink("Add new album", "Create", "Album")
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RecordFormat)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RecordFormat)
            @Html.ValidationMessageFor(model => model.RecordFormat)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript">
    $("#ArtistID").on('change', function () {
        if ($("#ArtistID").val().toString() != ""){
            var url = "AjaxGetAlbumsFromArtist/" + $("#ArtistID").val().toString();
            $.ajax({
                url: url,
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: successFunc,
                error: errorFunc
            });
        }
    }
    );

    function successFunc(data, status) {
        var ids = [];
        var titles = [];
        $("#albumSelectDiv").removeAttr("hidden");
        $("#AlbumID").empty();
        if (data.hasOwnProperty("ids") && data.hasOwnProperty("titles")) {
            if (data.ids.length > 0 
                && data.titles.length > 0 
                && data.titles.length == data.ids.length) {
                for (var i = 0; i < data.ids.length; i++) {
                    $("#AlbumID").append(new Option(data.titles[i], data.ids[i]));
                }
                
            }
        }
    }

    function errorFunc(data, status) {

    }
</script>

IDEIMusic/IDEIMusic/Views/Record/Delete.cshtml
@model IDEIMusic.Models.Record

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Record</legend>

    <div>
        <div class="display-label">
            @Html.DisplayNameFor(model => model.Album.Artist.Name)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Album.Artist.Name)
        </div>
    </div>

    <div>
        <div class="display-label">
            @Html.DisplayNameFor(model => model.Album.Title)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Album.Title)
        </div>
    </div>

    <div>
        <div class="display-label">
            @Html.DisplayNameFor(model => model.Price)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Price)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.DisplayNameFor(model => model.RecordFormat)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.RecordFormat)
        </div>
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

IDEIMusic/IDEIMusic/Views/Record/Details.cshtml
@model IDEIMusic.Models.Record

@{
    ViewBag.Title = "Record nr. " + Model.RecordID;
}

<h2>Record Details</h2>

<fieldset>
    <legend>Record</legend>

    <div>
        <div class="display-label">
            @Html.DisplayNameFor(model => model.Album.Artist.Name)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Album.Artist.Name)
        </div>
    </div>

    <div>
        <div class="display-label">
            @Html.DisplayNameFor(model => model.Album.Title)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Album.Title)
        </div>
    </div>

    <div>
        <div class="display-label">
            @Html.DisplayNameFor(model => model.Price)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Price)
        </div>
    </div>
    <div>
        <div class="display-label">
            @Html.DisplayNameFor(model => model.RecordFormat)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.RecordFormat)
        </div>
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.RecordID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

IDEIMusic/IDEIMusic/Views/Record/Edit.cshtml
@model IDEIMusic.Models.Record

@{
    ViewBag.Title = "Edit Record";
}

<h2>Edit Record</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Record</legend>

        @Html.HiddenFor(model => model.RecordID)

        @Html.HiddenFor(model => model.AlbumID)

        <div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Album.Artist.Name)
            </div>
            <div class="editor-field">
                @Html.DisplayFor(model => model.Album.Artist.Name)
            </div>
        </div>

        <div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Album.Title)
            </div>
            <div class="editor-field">
                @Html.DisplayFor(model => model.Album.Title)
            </div>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RecordFormat)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RecordFormat)
            @Html.ValidationMessageFor(model => model.RecordFormat)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IDEIMusic/IDEIMusic/Views/Record/Index.cshtml
@model IEnumerable<IDEIMusic.Models.Record>

@{
    ViewBag.Title = "Records";
}

<h2>Records</h2>

<p>
    @Html.ActionLink("Add new Record", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Album.Artist.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Album.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RecordFormat)
        </th>
        <th>
            Tags
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr class="tableRow">
            <td>
                @Html.ActionLink(item.Album.Artist.Name, "Details", "Artist", new { id = item.Album.Artist.ArtistID }, null)
            </td>
            <td>
                @Html.ActionLink(item.Album.Title, "Details", "Album", new { id = item.Album.AlbumID }, null)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RecordFormat)
            </td>
            <td>
                @foreach (var t in item.Album.Tags)
                {
                    @Html.ActionLink(t.Text, "Details/" + t.TagID, "Tag")

                }
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.RecordID }) |
                @Html.ActionLink("Details", "Details", new { id = item.RecordID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.RecordID })
            </td>
        </tr>
    }

</table>